name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '19 8 * * *' # Every day at 08:19 UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # Time before marking as stale
          days-before-stale: 30
          # Time before closing after marked stale
          days-before-close: 7

          # Messages
          stale-issue-message: >
            👋 This issue has been inactive for 30 days and is now marked as stale.
            If no further activity occurs, it will be closed in 7 days.
            Thank you for contributing!
          stale-pr-message: >
            👋 This pull request has been inactive for 30 days.
            It will be closed in 7 days unless updated.

          # Labels
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'

          # Options
          remove-stale-when-updated: true
          close-issue-message: 'Closing this issue due to prolonged inactivity.'
          close-pr-message: 'Closing this pull request due to inactivity.'
          exempt-issue-labels: 'pinned,important'
          exempt-pr-labels: 'do-not-close'
